### ISSUE TITLE
web UI resfresh loop

### ISSUE THREAD

**Issue by nbonacchi** [syncthing/syncthing-gtk#56] opened 2014-12-30 14:59 UTC
ubuntu 14.04, syncthing-gtk recently upgraded the deamon to v0.10.14 
if I load web ui (in either chrome, chromium or firefox) it keeps refreshing ad eternum and almost max's out cpu usage in my laptop and uses 2 full cores on my desktop, I'm not sure what the deamon is doing but it seems to be stuck in loading the UI and not necessarily scanning the folders.
If I run the daemon by itself from shell I have no problems.
I think this only happens if no other node are connected as I have synced stuff with this daemon version and don't recall encountering this issue.

**Comment by kozec** [comment] 2015-01-01 11:43
Ok, sorry, but no matter what I do, I can't reproduce this.

I'm on freshly installed Ubuntu 14.04 with `Syncthing-GTK 0.5.5-1~webupd8~trusty0`. First of all, deamon v0.10.14 is really not being downloaded...

```
I App           Checking for updates...
I StDownloader  Not using latest, unsupported Syncthing version v0.10.14; Using v0.10.13 instead
I App           Updatecheck: needs_upgrade = False
```

... and even if I update it manually, there is no refresh loop no matter how many (including zero) nodes are connected.

Can you, please, try to clean your browser cache to check if this is not WebUI problem after all?

**Comment by kozec** [comment] 2015-01-04 19:12
So... Any info, log or anything? Do you still have same problem? If not, I would like to close this and allow ST-GTK to use new Syncthing releases...

**Comment by nbonacchi** [comment] 2015-01-05 12:26
Ok, yes sorry, HAPPY NEW YEAR!!...

Anywho, something changed since I was partying, I don't seem to have the problem anymore. This is before clearing cache, (cleared it anyway), also the upgrade was made from the web interface which now tells me there is a new version (0.10.17), but unlike previously if I click on the upgrade link button it does nothing... well, it thinks about it, I mean it checks and nothing happens, If I restart the daemon (all from web UI) if does the refresh thing a couple of times (uses all cores for a while) and then stabilizes, notification of update is gone output shows updated version:
[Z7WIP] 12:09:56 INFO: syncthing v0.10.17 (go1.4 linux-amd64 default) unknown-user@syncthing-builder 2015-01-04 19:18:14 UTC

I guess that if users are not supposed to update from web UI somehow the notifications should be removed, not sure how though, I imagine you don't want to fork syncthing, but maybe if gtk would map exactly the web UI, the only reason I open the web UI is because it gives me more accurate readings of the state of my shared folders gtk will show "Idle" on the shared folders column while web UI will show "up to date", also nodes that disconnect keep their 'status' e.g. "Syncing ##%" while the web UI tells me the node is "Disconnected", I believe if I restart gtk it will display the correct info so maybe its some sort of refresh problem? (also the color of the appindicator icon does not refresh to gray when no node is connected unless I restart the app)....

I guess that answering to your question, you can close this, yes, the problem seems gone for now.
Thanks

**Comment by kozec** [comment] 2015-01-05 12:30
Ah, yeah, dunno why I didn't expect anyone clicking that... I'll look into disabling that popup.

Anyway, update problems from WebUI were mentioned at syncthing/syncthing#1175 . It shouldn't affect updates handled by Synthing-GTK.

**Closed by kozec** 2015-01-05 12:30 UTC
