### ISSUE TITLE
Added directories not saved to config.xml

### ISSUE THREAD

**Issue by TeutonJon78** [syncthing/syncthing-gtk#280] opened 2016-06-20 01:21 UTC
Syncthing-gtk 0.9.0.2-0.9.0.3

I shared a folder from a desktop install to a laptop install. On the laptop, it asked me if I wanted to add the shared folder. I replied yes, and it began running through the sync which completed. However, the changes were never written into the config.xml file -- the file remained unchanged in modification time. If I close the program and restart it, the newly accepted directory is now longer there and it was again asking me if I wanted to add it again. This can be repeated.

It never asked me to the save the configuration and restart the daemon like it does if you edit a setting on an existing directory.

I went into the actual web interface to add the directory (launching syncthing.exe manually), and it edited the config.xml file to add the directory, and it shows up in the syncthing-gtk window correctly on restarts.

On a side note, this directly had been added correctly in syncthing-gtk 0.8 in the past, but I had to do a reinstall on the laptop and did so with the 0.9 branch.

edit: add missing "-gtk"

**Comment by kozec** [comment] 2016-06-20 07:26
Wait, wait, wait. Syncthing 0.9? As in two years old version of Syncthing? Why?

**Comment by TeutonJon78** [comment] 2016-06-20 21:36
I meant syncthing-gtk (which is also stated later in the bug report). The versions I gave match up with that. The syncthing binary have all been in the 0.13.x branch since this problem as been happening.

syncthink-gtk 0.8 with syncthing 0.12 showed none of this problem.

**Comment by kozec** [comment] 2016-06-25 08:55
Sorry for late answer and sorry it's gonna be unpleasant one - I can't reproduce this at all.

So, some questions:

- Was synchronisation started, actually transfering some files? That would mean that ST-GTK successfully sent configuration to syncthing daemon and syncthing started using it, but failed to store it in file for some reason. ST-GTK doesn't actually write to syncthing's `config.xml`
- What was folder ID of that directory?
- Does path to it contain any non-ascii characters, spaces or anything but letters and numbers?
- What distro?

**Comment by TeutonJon78** [comment] 2016-06-25 15:36
The synchronization had already completed fully and it said "up to date". It happened once where the files needed to be transfered completely. And it happened a second time when the files were already transferred and it just wanted to readd the directory. Your statement is correct -- it send the sync information correctly but didn't modify the config.xml -- verifying the file modification time after adding it showed it had not been modified, and the contents did not have the new directory.

the folder is was bob-music. The path would have contained some spaces but all valid NTFS characters.

Sorry I forgot to mention this was on Windows 10 Home (64-bit) on both computers involved.

And again, the same setup worked find if I added the directory from within the syncthing web interface (config.xml was updated and it immediately asked me to restart the daemon) while adding it from syncthing-gtk never asked me to restart (probably because the config.xml write wasn't being triggered). Once the directory was actually added to the file, it showed up on syncthing-gtk restarts as expected.

This happened on earlier syncthing 0.13.x as well as 0.13.6.

**Comment by kozec** [comment] 2016-06-28 08:11
I'm sorry, but I really can't make any sense from it...

@AudriusButkevicius sorry to bother you, but would you happen to know about any possible case, when POSTing to 'system/config' would cause syncthing to *use* sent config, but not to save it to config.xml?

**Comment by AudriusButkevicius** [comment] 2016-06-28 08:14
When the config is not writable.

**Comment by kozec** [comment] 2016-06-28 08:19
Soo... Even in case when config.xml is "locked" by being already open by another process? Windows tends to do that sometimes and I guess syncthing would not retry writing later or anything like that.

**Comment by AudriusButkevicius** [comment] 2016-06-28 08:22
It tries to write it out when something changes, and not all cases will report errors.

**Comment by acolomb** [comment] 2016-07-12 07:36
I just had a similar problem on Windows 7, using Syncthing-GTK v0.9.0.3-win32, Syncthing v0.13.10.

I deleted the "default" folder from within the GTK GUI. After refreshing the web interface, it was gone there, too. After restarting Syncthing, the "default" folder ID is back with all its config settings. The config file at C:\Users\IFT\AppData\Local\Syncthing\config.xml was not modified. Deleting from within the Web UI shows the same behaviour--folder reappears after restart and config file is not written.

This is probably a Syncthing bug. @kozec, do you have any more instructions for investigating the bug, before we forward it to Syncthing?

**Comment by AudriusButkevicius** [comment] 2016-07-12 07:52
Is your config file actually in a writable location? 
I suspect it's not. Also habe you checked syncthing log for errors?

**Comment by acolomb** [comment] 2016-07-12 08:10
I can edit the file without problems using a text editor. Syncthing-GTK is started as the same user.

No errors in the syncthing log, as shown from St-GTK. Interestingly, the folder removal is not logged either.

In the same directory as the config file, there is a syncthing.log file, but it was last written in 2014 by Syncthing v0.10.9. Where is the current one?

**Comment by AudriusButkevicius** [comment] 2016-07-12 08:14
Syncthing logs to stdout by default.

**Comment by kozec** [comment] 2016-07-12 08:18
> Syncthing logs to stdout by default.

Syncthing-GTK captures that and displays it in window accessible from left menu -> Display Daemon Output.

[this menuitem](http://pasteboard.co/avDacryVK.png)

**Comment by acolomb** [comment] 2016-07-12 08:19
Well then there are certainly no error messages related to the removed folder. Not even an INFO message that it was removed.

**Comment by AudriusButkevicius** [comment] 2016-07-12 08:24
There would be no info message. Can you check if the config file has the folder after removing it?

**Comment by acolomb** [comment] 2016-07-12 08:29
Yes, it's still in there, the file does not change.

I tried with `STTRACE=scanner,main,config`. It shows some "verifying configuration" and then "committing configuration" messages, along with reconnection to all peers. No error message for failing to write the config file.

@kozec It seems that specifying `-logfile=D:\path\file.log` in the advanced daemon settings tab is not effective? Does ST-GTK override that specific command line flag?

**Comment by kozec** [comment] 2016-07-12 08:35
> @kozec It seems that specifying -logfile=D:\path\file.log in the advanced daemon settings tab is not effective? Does ST-GTK override that specific command line flag?

Kinda. ST-GTK enables STNORESTART environment variable, which disables Syncthing "managing" process and that in turn disables -logfile, because "managing" process is what actually creates that log.

**Comment by acolomb** [comment] 2016-07-12 08:36
Then there might be a need to document this behaviour :-)

**Comment by kozec** [comment] 2016-07-12 08:37
> Then there might be a need to document this behaviour :-)

Frankly, I wasn't aware of that until you asked :D

**Comment by AudriusButkevicius** [comment] 2016-07-12 08:37
So I cannot reproduce what you are describing(and I am sure there would be another 10 issues open regarding this if others could), therefore it must be something specific to your setup.

Perhaps you should try capturing an strace and see what happens when it tries to write the file.

**Comment by acolomb** [comment] 2016-07-12 08:41
Well I knew of this bug report when encountering the problem this morning, so there are at least two users already with similar problems and probably the same cause.

Is there an strace utility available for Windows 7? So far I've tried ProcessExplorer from sysinternals.com, but I can't even get it to show the open file handles...

**Comment by acolomb** [comment] 2016-07-12 09:08
Ok, so the ProcessMonitor [1] shows some `CreateFile` events for `config.xml`. Mostly the result is `NOT A DIRECTORY`, there is one `SHARING VIOLATION` entry, followed by some `SUCCESS` results. The `SHARING VIOLATION` happens in `syncthing.exe + 0xa2f5a`, according to the stack trace.

There must be a way to provide a log file with only the relevant information... So far I could only dump an XML file with info about all running processes on the system :-(

1: https://technet.microsoft.com/de-de/sysinternals/processmonitor.aspx

**Comment by acolomb** [comment] 2016-07-12 09:09
Whatever the root cause may be, Syncthing should definitely check if the file write was successful and report an error otherwise, no?

**Comment by acolomb** [comment] 2016-07-12 09:15
Hm... trying to reproduce the error again, it now worked. config.xml got updated and ProcessMonitor showed only SUCCESS results.

**Comment by AudriusButkevicius** [comment] 2016-07-12 09:27
Sharing violation implies that the file is locked by something.

**Comment by AudriusButkevicius** [comment] 2016-07-12 09:28
I don't think syncthing opens files in exclusive mode. Do you have an antivirus or something like thay tapping into the files?

**Comment by acolomb** [comment] 2016-07-12 09:34
Yes, that would be my best guess as well. There is an antivirus scanner active which I probably can't disable (employer's machine). Attached screenshot shows the successful and failed write attempts in ProcessMonitor. Note that syncthing was started without the GTK wrapper in this case.

Would it make sense to lock the config file while Syncthing is running?
![procmon-syncthing_failed-config-write](https://cloud.githubusercontent.com/assets/6996887/16762386/8c2119da-4824-11e6-92b4-e016b7ea7bf5.png)

**Comment by AudriusButkevicius** [comment] 2016-07-12 09:57
Afaik Go doesn't have a way to do that, and I don't see a reason to lock the file just to work around poor antivirus software.

We should however log failures.

**Comment by kozec** [comment] 2016-07-12 10:13
> We should however log failures.

There is reason why ST-GTK logs 'Configuration (**probably**) saved' from `/rest/config` post callback :)

With some nice error message, it can even send that configuration repeatedly or display scary-looking error window.

**Comment by AudriusButkevicius** [comment] 2016-07-12 20:55
Potentially related perhaps? 
https://github.com/syncthing/syncthing-inotify/issues/118

**Comment by TeutonJon78** [comment] 2016-07-16 06:30
I can say for my original report, syncthing-inotify was indead running for the directories I had setup (0 scan time).

When I ran syncthing manually, would it also startup inotify, or is that only started up manually or via something like syncthing-gtk?

**Comment by kozec** [comment] 2016-07-16 06:44
> When I ran syncthing manually, would it also startup inotify, or is that only started up manually or via something like syncthing-gtk?

You have to start it manually. If you closed ST-GTK and ran only Syncthing, syncthing-inotify was most likely not active at that time.

**Comment by kozec** [comment] 2016-07-18 07:15
With latest daemon rc, HTTP500 with actual error is reported:

```
<<< HTTP/1.0 500 Internal Server Error
Cache-Control: max-age=0, no-cache, no-store
Content-Type: text/plain; charset=utf-8
Expires: Mon, 18 Jul 2016 07:01:49 GMT
Pragma: no-cache
X-Content-Type-Options: nosniff
X-Syncthing-Id: SOME-THING-CENSO-RED42
X-Syncthing-Version: v0.14.0-rc.1
Date: Mon, 18 Jul 2016 07:01:50 GMT
Content-Length: 163

remove C:\Users\user\AppData\Local\Syncthing\config.xml: Process cannot access the file because it is being used by another process
```

So, this really is mainly syncthing-inotify issue, which is fixed, but not yet released.

**Comment by acolomb** [comment] 2016-07-18 14:52
At least in my last tests quoted above, I am fairly sure that Syncthing-inotify was **NOT** running. I had started `syncthing.exe` from the command line to see the output log directly. Could have been that a stray instance of st-inotify was still running after closing ST-GTK.

**Comment by kozec** [comment] 2016-07-18 14:58
@acolomb Try it with syncthing release v0.14.0-rc.1, it should report error message that can be seen in Network tab of browser developer tools.

**Closed** 2016-08-23 11:41 UTC
Labels: info needed
