### ISSUE TITLE
Some folders are stuck in "syncing" state after other nodes re-connect

### ISSUE THREAD

**Issue by eugenesan** [syncthing/syncthing-gtk#281] opened 2016-06-22 14:01 UTC
Recently I've noticed that frequently some folders are stuck in "Syncing" state after other nodes reconnect while at the same time Web-UI is in "Up to date" state.

**Comment by kozec** [comment] 2016-06-25 08:43
Sorry, but is there any way how to reproduce this reliably? I just restarted 4 syncthing instances 16 times and everything goes offline as it should...

**Comment by eugenesan** [comment] 2016-06-25 22:36
Thanks for looking into it.
Unfortunately, I still have no idea how the issue is triggered but here are few observations:
1. Seems like peers re-connection is not the trigger. Till now the issue appeared mainly (if not only) after system suspend-resume (hence unexpected daemon re-init).
2. It's always the same folder which is the biggest and therefor always the last to finish initial scan (~5 seconds longer).
3. While the folder appears to be in "syncing" state, all of the peers are in "up to date" state.
4. Web-UI and daemon log show no sign of any syncing process.

**Comment by kozec** [comment] 2016-06-26 09:46
> 1. Seems like peers re-connection is not the trigger. Till now the issue appeared mainly (if not only) after system suspend-resume (hence unexpected daemon re-init).

In that case, it may get fixed along with #265 after event pulling recode that I'm trying to make work for much longer than I originally imagined :D

**Comment by vacore** [comment] 2017-02-16 13:06
Looks like I'm experiencing the same issue, the Syncthing-GTK simply stops updating its Folder's state in GUI in some time after syncing start. I've started bulk sync of several GBs on a freshly installed system. I'm using Linux Mint Cinnamon 18.1, Syncthing-GTK, v.0.9.2.4 (Daemon 0.14.23).
Web-UI always shows correct info.

**Comment by kozec** [comment] 2018-02-24 10:34
This should be fixed with latest release.

**Closed by kozec** 2018-02-24 10:34 UTC
Labels: info needed
