### ISSUE TITLE
Missing desktops notifications

### ISSUE THREAD

**Issue by nbrownus** [syncthing/syncthing-gtk#236] opened 2016-01-07 01:19 UTC
Seems like sync actions that take longer than some polling interval make it to a desktop notification. If I create a couple of small files I never get a desktop notification but the files appear locally.

**Comment by kozec** [comment] 2016-01-07 08:19
That may be by design, when new notification is generated sooner than 5s after previous, they are merged together to prevent flooding screen with them. You should get notification about "X files updated" when jumping over files slows down.

**Closed** 2016-01-18 08:19 UTC
